CopyDots fix

diff --git a/CopyDots b/CopyDots
--- a/CopyDots
+++ b/CopyDots
@@ -5,23 +5,6 @@
 # Copy dot files to git dir with optional push
 
 
-# Directories to copy
-if [ "$1" = "bspwm" ]; then
-    declare -a dirs=(".config/bspwm" ".config/sxhkd" ".config/neofetch" ".config/polybar" ".vimrc" ".xinitrc" ".Xresources" ".zprofile" ".zshrc")
-elif [ "$1" = "i3" ]; then
-    declare -a dirs=(".config/i3" ".config/polybar" ".vimrc" ".xinitrc" ".Xresources" ".zprofile" ".zshrc")
-fi
-
-
-# Start main script
-####################################################################################
-
-copy_directory()
-{
-    echo "Copying $1"
-    cp -r "$HOME/$1" "$HOME/Scripts/Dot-Files"
-}
-
 # Get enviroment from the user
 if [ "$1" != "" ]; then
     branch="$1"
@@ -34,6 +17,26 @@ do
     echo "Choose an enviroment"
     read branch
 done
+
+# Directories to copy
+if [ "$branch" = "bspwm" ]; then
+    declare -a dirs=(".config/bspwm" ".config/sxhkd" ".config/neofetch" ".config/polybar" ".vimrc" ".xinitrc" ".Xresources" ".zprofile" ".zshrc")
+elif [ "$branch" = "i3" ]; then
+    declare -a dirs=(".config/i3" ".config/polybar" ".vimrc" ".xinitrc" ".Xresources" ".zprofile" ".zshrc")
+else
+    (echo "Invalid branch." >&2)
+    exit 1
+fi
+
+
+# Start main script
+####################################################################################
+
+copy_directory()
+{
+    echo "Copying $1"
+    cp -r "$HOME/$1" "$HOME/Scripts/Dot-Files"
+}
 
 # Copy each directory listed in dirs array
 for dir in "${dirs[@]}"
